### PR TITLE
install latest kerbrute directly using go install ...@latest

### PR DESCRIPTION
**Pull request by yechielw**

### CODE REVIEW

**Comment by IppSec** [comment]
Thanks.  I will merge this when I do my video on cleaning up the playbook.

**Comment by h34rtb34t** [comment]
vscode installation error:    

failed: [localhost] (item=az87: streetsidesoftware.code-spell-checker) => {"ansible_loop_var": "item", "changed": false, "item": [{"username": "az87"}, "streetsidesoftware.code-spell-checker"], "msg": "Error querying installed extensions [streetsidesoftware.code-spell-checker]: You are trying to start Visual Studio Code as a super user which isn't recommended. If this was intended, please add the argument `--no-sandbox` and specify an alternate user data directory using the `--user-data-dir` argument.\n"}
failed: [localhost] (item=az87: ms-python.python) => {"ansible_loop_var": "item", "changed": false, "item": [{"username": "az87"}, "ms-python.python"], "msg": "Error querying installed extensions [ms-python.python]: You are trying to start Visual Studio Code as a super user which isn't recommended. If this was intended, please add the argument `--no-sandbox` and specify an alternate user data directory using the `--user-data-dir` argument.\n"}
failed: [localhost] (item=az87: DEVSENSE.phptools-vscode) => {"ansible_loop_var": "item", "changed": false, "item": [{"username": "az87"}, "DEVSENSE.phptools-vscode"], "msg": "Error querying installed extensions [DEVSENSE.phptools-vscode]: You are trying to start Visual Studio Code as a super user which isn't recommended. If this was intended, please add the argument `--no-sandbox` and specify an alternate user data directory using the `--user-data-dir` argument.\n"}
failed: [localhost] (item=az87: GitHub.copilot-nightly) => {"ansible_loop_var": "item", "changed": false, "item": [{"username": "az87"}, "GitHub.copilot-nightly"], "msg": "Error querying installed extensions [GitHub.copilot-nightly]: You are trying to start Visual Studio Code as a super user which isn't recommended. If this was intended, please add the argument `--no-sandbox` and specify an alternate user data directory using the `--user-data-dir` argument.\n"}
failed: [localhost] (item=az87: snyk-security.snyk-vulnerability-scanner) => {"ansible_loop_var": "item", "changed": false, "item": [{"username": "az87"}, "snyk-security.snyk-vulnerability-scanner"], "msg": "Error querying installed extensions [snyk-security.snyk-vulnerability-scanner]: You are trying to start Visual Studio Code as a super user which isn't recommended. If this was intended, please add the argument `--no-sandbox` and specify an alternate user data directory using the `--user-data-dir` argument.\n"}

THE ERROR SPEAKS LOUD&CLEAR but it took me a while to get the your ansible script running; here is how i've modified the main.yml:


 cat main.yml 
- name: "Customizing Parrot"
  hosts: localhost
  connection: local
  roles:
    - role: "roles/configure-tmux"
    - role: "roles/customize-terminal"
    - role: "roles/install-tools"
    - role: "roles/customize-browser"
    - role: "roles/configure-logging"
  tasks:
    - name: Install Visual Studio Code extensions
      become: false
      command: "code --no-sandbox --user-data-dir=/home/az87/Desktop"
      vars:
        visual_studio_code_extensions:
          - streetsidesoftware.code-spell-checker
          - ms-python.python
          - DEVSENSE.phptools-vscode
          - GitHub.copilot-nightly
          - snyk-security.snyk-vulnerability-scanner

AND NOW THE 'ANSIBLE-PLAYBOOK MAIN.YML' WENT ALLLLLL THE WAY THROUGH WITH NO ERRORS; NOW I'M RUNNING a fully fledged Ippsec ParrotOS HTB Edition VM

**Comment by IppSec** [comment]
@h34rtb34t I believe you were running 
```sudo ansible-playbook main.yml```

You should not run the ansible command itself as root.

**Comment by h34rtb34t** [comment]
IF I DON'T RUN IT AS ROOT, i would eventually get an other error related to ''.Burpsuit'' folder saying that it can not access it unlesse it is root...

**Pull request merged**
